FROM maven:3.9.9-amazoncorretto-23 AS build

COPY RentMicroService /app

WORKDIR /app

RUN mvn clean package -Dmaven.test.skip=true

FROM openjdk:23

COPY --from=build /app/Applications/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]